### ISSUE TITLE
Get rid of `clean_str`

### ISSUE THREAD

**Issue by dafky2000** [glest/glest-masterserver#1]
Only used in a handful of places to remove different specific characters... Seems pretty overkillish and as the comment mentions, will likely cause more problems than it solves. 

https://github.com/ZetaGlest/zetaglest-masterserver/blob/c8717d3a5df60f623b454de020090cfededde149/functions.php#L9

**Comment by andy5995** [comment]
Thanks for the suggestion. ticket labelled and accepted.

**Comment by martijndeb** [comment]
I think if one wants to fix this properly, it either needs to get removed and accept the things it might break. Or just allow a-Z0-9 and a dash. Otherwise it's just overkill yes. I'd say don't touch it if no problems are caused.

**Comment by andy5995** [comment]
>I'd say don't touch it if no problems are caused.

There haven't been any problems that I've noticed.
