### ISSUE TITLE
IP addresses don't need to be shown on the web

### ISSUE THREAD

**Issue by andy5995** [glest/glest-masterserver#10]
The field that displays IP address of the server and players can be removed.

https://zetaglest.dreamhosters.com/

**Comment by pushkar-anand** [comment]
I would like to take up this issue.

**Comment by andy5995** [comment]
ok, it's still open.

**Comment by andy5995** [comment]
Oh, I just realized... could you also remove the `Game protocol port` column as part of your PR?

**Comment by pushkar-anand** [comment]
Yes sure.

**Comment by yannik995** [comment]
This change should be made in the PHP code, as the IP address can otherwise be seen in the HTML source code.

**Comment by pushkar-anand** [comment]
Okay, I will remove it completely.

**Comment by pushkar-anand** [comment]
I updated my code. #12

**Comment by andy5995** [comment]
@yannik995 we typically try to merge PRs from people who first offered on the ticket. This helps save people time and prevent duplicate pull requests. It's explained more in our CONTRIBUTING document. https://github.com/ZetaGlest/zetaglest-source/blob/develop/CONTRIBUTING.md#issues

I appreciate your help with this though. I plan to be opening more tickets on this repo very soon, so you may want to keep an eye on things.
