### ISSUE TITLE
banner image should be placed at the top

### ISSUE THREAD

**Issue by andy5995** [glest/glest-masterserver#14]
Our banner logo should be placed at the top, and the text link removed, replaced with this graphic:

https://raw.githubusercontent.com/ZetaGlest/zetaglest.github.io/master/docs/assets/images/zetaglest_logo_412x207.png

Don't copy the graphic, just hotlink to to it. The width and height attributes should be added to the img tag and the title attribute should read ZetaGlest home page. The graphic should link back to https://github.com/ZetaGlest

Please remember to "star" this project. Our contributing guidelines are in our primary source code repo at https://github.com/ZetaGlest/zetaglest-source/blob/develop/CONTRIBUTING.md

**Comment by mohancm** [comment]
@andy5995 please verify my commit #15 
thank you
