### ISSUE TITLE
link back to main needed

### ISSUE THREAD

**Issue by andy5995** [glest/glest-masterserver#20]
At the top of https://zetaglest.dreamhosters.com/showPlayers.php, an additional link back to 

the [main page](https://zetaglest.dreamhosters.com/) is needed. The link could be on the left, next to the "day, week, month" links. The link text should be "Games List".

**Comment by leeyspaul** [comment]
Hey @andy5995, I'd love to take up this issue!

**Comment by mike-k0** [comment]
I'll give this a shot if you don't mind!

**Comment by mathusummut** [comment]
[This is now resolved](https://github.com/glest/glest-masterserver/commit/9acfb32f7f381c733d5adc310d1a90c1cad7802f)
