### ISSUE TITLE
clicking the "Finished" link doesn't collapse the details

### ISSUE THREAD

**Issue by andy5995** [glest/glest-masterserver#8]
Clicking the "Finished" link doesn't collapse the details. Clicking it once expands the details; clicking it a 2nd time should collapse them.

https://zetaglest.dreamhosters.com/

It seems there should be a plus sign next to the word "finished", with a tooltip statiing "click to show details"; and "finished" should not have a hyperlink.

Once expanded, the + should be a minus sign, tooltip saying "show less" or something to that effect.

If you're interested in working on this, please post on this ticket before you start.

*Please remember to **star** this project (upper right-hand corner)*

**Comment by Expelliarmus98** [comment]
@andy5995 I would like to work on this.Is it still open?

**Comment by andy5995** [comment]
Yes. It's all yours.

**Comment by Expelliarmus98** [comment]
@andy5995, I am sorry to disturb you.I am unable to find the files in the repository. This is my first issue. Could you let me know where I am supposed to look for them?

**Comment by andy5995** [comment]
https://github.com/ZetaGlest/zetaglest-masterserver/blob/develop/scripts/utils.js#L29

**Comment by andy5995** [comment]
completed by @craigpotter in https://github.com/ZetaGlest/zetaglest-masterserver/pull/17
